=== aleahdeguzman/random-sandbox/XmlXsd/src/main/java/org/jubot/xsd/student_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.org.jubot/student_schema" 
xmlns="http://www.org.jubot/student_schema" 
elementFormDefault="qualified">

<xs:element name="student">
	<xs:complexType>
		<xs:complexContent>
			<xs:extension base="person">
				<xs:sequence>
					<xs:element name="studentno" type="xs:integer"/>
					<xs:element name="subjects" type="subject"/>
					<xs:element name="course">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="ICS"/>
								<xs:enumeration value="HRM"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:element>

<xs:complexType name="subject">
	<xs:sequence>
      <xs:element name="subject" type="xs:string" maxOccurs="5" /> 
	</xs:sequence>
</xs:complexType>

<xs:complexType name="person">
	<xs:sequence>
		<xs:element name="name">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="20"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="age" type="xs:string"/>
		<xs:element name="bday" type="xs:date"/>
	</xs:sequence>
</xs:complexType>

</xs:schema>

=== aleahdeguzman/random-sandbox/XmlXsd/src/main/java/org/jubot/xml/Student.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:student xmlns:p="http://www.org.jubot/student_schema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.org.jubot/student_schema student_schema.xsd ">
  <p:name>Frances Aleah</p:name>
  <p:age34e</p:age>
  <p:bday>1979-03-20</p:bday>
  <p:studentno>1</p:studentno>
  <p:subjects>
    <p:subject>Math</p:subject>
    <p:subject>English</p:subject>
    <p:subject>Science</p:subject>
  </p:subjects>
  <p:course>ICS</p:course>
</p:student>
